In [5]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
np.flip(arr)

array([5, 4, 3, 2, 1])

In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[1,3],[3,4]])
a1==a2

array([[ True, False],
       [ True,  True]])

In [21]:
np.array_equal(a1,a2)

False

In [27]:
x=np.array([1,2,3,4,5,1,2,1,1,1,5,5,5,5,5,5,5])
count=np.bincount(x)
print(np.argmax(count))
y=np.argmax(count)
ind=np.where(x==y)[0]
ind

5


array([ 4, 10, 11, 12, 13, 14, 15, 16], dtype=int64)

In [29]:
values, counts = np.unique(x, return_counts=True)

ind = np.argmax(counts)
print(values[ind]) 

5


In [31]:
arr=np.array([[55,25,15],[30,44,2],[11,45,77]])
arr

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [35]:
d=np.diagonal(arr)
print(sum(d))

176


In [37]:
print(np.trace(arr))

176


In [39]:
eigval,eigvec=np.linalg.eig(arr)
print(eigval)
print(eigvec)

[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [42]:
print(np.linalg.inv(arr))
print(np.linalg.det(arr))

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [51]:
p=np.array([[1,2],[3,4]])
q=np.array([[4,5],[6,7]])
p*q #element wise hota h
np.multiply(p,q) #yaha bhi

array([[ 4, 10],
       [18, 28]])

In [52]:
print(np.matmul(p,q))

[[16 19]
 [36 43]]


In [57]:
x=np.array([[1,2],[2,3],[4,5]])
y=np.array([[4,5,1],[6,7,2]])
np.matmul(x,y) #only matmul works here

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

In [60]:
#error in x,y
print(np.cov(p,q))

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [64]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))
print(np.meshgrid(x,y)) #cartesian

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]
[array([[2, 3, 4, 3, 2, 9],
       [2, 3, 4, 3, 2, 9],
       [2, 3, 4, 3, 2, 9],
       [2, 3, 4, 3, 2, 9],
       [2, 3, 4, 3, 2, 9],
       [2, 3, 4, 3, 2, 9]]), array([[ 1,  1,  1,  1,  1,  1],
       [ 5,  5,  5,  5,  5,  5],
       [ 0,  0,  0,  0,  0,  0],
       [ 5,  5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10, 10],
       [ 3,  3,  3,  3,  3,  3]])]


In [72]:
b=np.array([[-1,-4,2],[7,-8,9]])
print(np.abs(b))
x=b.flatten()
x
perc_f=np.percentile(x,[25,50,70])
print(perc_f)
perR=np.percentile(b,[25,50,70],axis=0) #column wise
print(perR)
perC=np.percentile(b,[25,50,70],axis=1)# row wise
print(perC)

[[1 4 2]
 [7 8 9]]
[-3.25  0.5   4.5 ]
[[ 1.   -7.    3.75]
 [ 3.   -6.    5.5 ]
 [ 4.6  -5.2   6.9 ]]
[[-2.5 -0.5]
 [-1.   7. ]
 [ 0.2  7.8]]


In [75]:
print(np.mean(x))
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))
print(np.median(x))
print(np.median(b,axis=0))
print(np.median(b,axis=1))
print(np.std(x))
print(np.std(b,axis=0))
print(np.std(b,axis=1))

0.8333333333333334
[ 3.  -6.   5.5]
[-1.          2.66666667]
0.5
[ 3.  -6.   5.5]
[-1.  7.]
5.927806414592913
[4.  2.  3.5]
[2.44948974 7.58653778]


In [76]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,-1.2,3.0,2.1])

In [77]:
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.around(a,decimals=0))

[-2. -2. -1.  0.  1. -2.  3.  2.]
[-1. -1. -0.  1.  2. -1.  3.  3.]
[-1. -1. -0.  0.  1. -1.  3.  2.]
[-2. -2. -0.  0.  2. -1.  3.  2.]


In [2]:
import numpy as np
x=np.array([10,52,62,16,16,54,445])
y=np.sort(x)
print(y)
print(np.argsort(x))
print(y[:4])
print(y[-5:])

[ 10  16  16  52  54  62 445]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 445]


In [12]:
av=np.array([1,0,1.2,2.2,2.0,3.0,2.0])

an=av[av==av.astype(int)]
an
ax=av[av!=av.astype(int)]
ax

array([1.2, 2.2])

In [15]:
import cv2
def img_to_array(path):
    img=cv2.imread(path,cv2.IMREAD_UNCHANGED)
    
    if img is None:
        print("error image not found")
        return
    if len(img.shape)==2:
        np.savetxt("grayscale image.txt",img,fmt='%d')
        print('grayscale image saved')
    elif len(img.shape)==3:
        np.savetxt('rgbimage.txt',img,fmt='%d')
        np.save('xyz.npy',img)
        print('rgb image saved')
    else:
        print('format not supported')